name: Build raylua_e for macOS x86_64

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build raylib-lua for x86_64
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.13
          export ARCHFLAGS="-arch x86_64"
          export CFLAGS="-arch x86_64 -mmacosx-version-min=10.13"
          export LDFLAGS="-arch x86_64 -mmacosx-version-min=10.13"

          cd luajit
          make clean MACOSX_DEPLOYMENT_TARGET=10.13
          make amalg BUILDMODE=static MACOSX_DEPLOYMENT_TARGET=10.13
          cd ..

          cd raylib/src
          make clean
          make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_33
          cd ../..

          make CC=clang CFLAGS="-O2 -Iluajit/src -Iraylib/src -Iraygui/src -Iphysac/src -DGRAPHICS_API_OPENGL_33 -DPLATFORM_DESKTOP -arch x86_64 -mmacosx-version-min=10.13" LDFLAGS="-O2 -lm luajit/src/libluajit.a raylib/src/libraylib.a -arch x86_64 -mmacosx-version-min=10.13 -framework Cocoa -framework IOKit -framework CoreVideo -framework OpenGL"

      - name: Upload raylua_e (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: raylua_e_macos_x86_64
          path: raylua_e
